apiVersion: v1
kind: Pod
metadata:
  name: devops-001-hello
  labels:
    name: devops-001-hello
spec:
  containers:
  - name: devops-001-hello
    image: mehmetarslan22/devops-001-hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
