apiVersion: v1
kind: Pod
metadata:
  name: my-pod-create
  labels:
    name: my-pod-create
spec:
  containers:
  - name: my-pod-create
    image: mehmetarslan22/devops-001-hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9091
---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-create-2
  labels:
    name: my-pod-create-2
spec:
  containers:
  - name: my-pod-create-2
    image: mehmetarslan22/devops-001-hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9092