apiVersion: v1
kind: Pod
metadata:
  name: my_pod_3
  labels:
    name: my_pod_3
spec:
  containers:
  - name: my_pod_3
    image: mehmetarslan22/devops-001-hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9091
---

apiVersion: v1
kind: Pod
metadata:
  name: my_pod_2
  labels:
    name: my_pod_2
spec:
  containers:
  - name: my_pod_2
    image: mehmetarslan22/devops-001-hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9092